#!/usr/bin/env bash

PIO_FS_BASEDIR=${HOME}/.pio_store
PIO_FS_ENGINESDIR=${PIO_FS_BASEDIR}/engines
PIO_FS_TMPDIR=${PIO_FS_BASEDIR}/tmp

SPARK_HOME=${PIO_HOME}/vendors/spark-${SPARK_VERSION}-bin-hadoop2.6

PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta
PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=SQLITE
PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME=pio_event
PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE=SQLITE
PIO_STORAGE_REPOSITORIES_MODELDATA_NAME=pio_model
PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE=SQLITE

PIO_STORAGE_SOURCES_SQLITE_TYPE=jdbc
PIO_STORAGE_SOURCES_SQLITE_URL=jdbc:sqlite::memory:
PIO_STORAGE_SOURCES_SQLITE_USERNAME=xxx
PIO_STORAGE_SOURCES_SQLITE_PASSWORD=xxx
